env:
  node: true
  es2021: true
  jest/globals: true
plugins:
  - jest
ignorePatterns:
  - "**/*.d.ts"
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2022
  sourceType: module
