env:
  node: true
  es2021: true
  jest/globals: true
plugins:
  - security
  - jest
ignorePatterns:
  - "**/*.test.js"
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 2021
