env:
  node: true
  es2021: true
  jest/globals: true
plugins:
  - security
  - jest
ignorePatterns:
  - "**/*.test.js"
extends:
  - eslint:recommended
  - prettier
  - plugin:security/recommended
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  security/detect-object-injection: 0
  security/detect-non-literal-fs-filename: 0
  security/detect-non-literal-require: 0
