name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 18, 19, 20, 21 ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v4
      - name: System info
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "yarn"
          yarn -v
          echo "yarn enableImmutableInstalls"
          yarn config get enableImmutableInstalls
      - name: Allow modify yarn.lock
        run: yarn config set -H enableImmutableInstalls false
      - name: Install modules
        run: yarn install
      - name: Run lint tasks
        run: |
          yarn lint
          yarn prettier
      - name: Run test
        run: yarn test
